version: '3.8'
services:
  postgres:
    container_name: db
    image: postgres:16-alpine
    # networks:
    #   - memobox-swarm
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d dbname']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6-alpine
    # networks:
    #   - memobox-swarm
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

# networks:
#   memobox-swarm:
#     external: true

volumes:
  postgres-data:
  redis-data:
