version: '3.8'
services:
  app:
    container_name: back-test
    build:
      context: .
      dockerfile: testing.Dockerfile
    ports:
      - '${APP_PORT}:3001'
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}

  db:
    image: postgres:16.0-alpine
    container_name: db-test
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_HOST=${DATABASE_HOST}
    ports:
      - '${DATABASE_PORT}:5432'

  redis-test-service:
    image: redis:6-alpine
    container_name: redis-test
    # ports:
    #   - '${REDIS_PORT}:6379'
    ports:
      - '6378:6379'
