version: '3.8'
services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: testing.Dockerfile
    # ports:
      # - '3033:${APP_PORT}'
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}

  db:
    image: postgres:16.0-alpine
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      # - POSTGRES_HOST=${DATABASE_HOST}
    # ports:
      # - '${DATABASE_PORT}:5432'

  redis:
    image: redis:6-alpine
    container_name: ${REDIS_CONTAINER_NAME}
    # ports:
    #   - '${REDIS_PORT}:6379'
    # ports:
      # - '6382:6379'
