version: '3.8'
services:
  backend-test:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: testing.Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db-test:
    build:
      context: .
      dockerfile: testing.db.Dockerfile
    # image: postgres:16-alpine
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db-backups:/backups # Используем тот же том для доступа к бэкапам

  redis-test:
    image: redis:6-alpine
    container_name: ${REDIS_CONTAINER_NAME}

volumes:
  db-backups: # Объявляем том
