version: '3.8'
services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - REDIS_URL=${REDIS_URL}
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  postgres:
    container_name: ${DATABASE_CONTAINER_NAME}
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d dbname']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis-prod:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: