version: '3.8'
services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: testing.Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: postgres:16.0-alpine
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  redis:
    image: redis:6-alpine
    container_name: ${REDIS_CONTAINER_NAME}
