services:
  # название сервиса
  postgres:
    # какой image используем
    image: postgres:16.0-alpine
    container_name: postgresDb
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - boilerplate-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  # название сервиса
  maildev:
    # описаываем какой Dockerfile используем и путь к нему
    build:
      context: .
      dockerfile: maildev.Dockerfile
      container_name: mailService
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379

  api:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: backendApi
    ports:
      - ${APP_PORT}:${APP_PORT}

volumes:
  boilerplate-db:
