version: '3.8'
services:
  app:
    container_name: back-test
    build:
      context: .
      dockerfile: testing.Dockerfile
    ports:
      - '${APP_PORT}:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - REDIS_URL=${REDIS_URL}

  db:
    image: postgres:16.0-alpine
    container_name: db-test
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:5432'

  redis:
    image: redis
    ports:
      - '6379:6379'
