version: '3.8'
services:
  app:
    container_name: back
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - REDIS_URL=${REDIS_URL}
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

    postgres:
      container_name: db
      image: postgres:16-alpine
      # ports:
      #   - 5432:5432
      restart: unless-stopped
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: dbname
      healthcheck:
        test: ['CMD-SHELL', 'pg_isready -U user -d dbname']
        interval: 10s
        timeout: 5s
        retries: 5
      volumes:
        - postgres-data:/var/lib/postgresql/data

  redis-prod:
    container_name: redis
    image: redis:6-alpine
    restart: unless-stopped
    # networks:
    #   - memobox-swarm
    # ports:
    #   - '6379:6379'
    volumes:
      - redis-data:/data
    # depends_on:
    #   redis:
    #     condition: service_started
    #   postgres:
    #     condition: service_healthy
volumes:
  postgres-data:
  redis-data: