/* cSpell:disable */
export const roles = [
  {
    id: 1,
    name: 'ADMIN',
  },
  {
    id: 2,
    name: 'USER',
  },
];

export const statuses = [
  {
    id: 1,
    name: 'ACTIVE',
  },
  {
    id: 2,
    name: 'INACTIVE',
  },
];

export const users = [
  {
    id: '321f06ed-c28e-48ee-9457-2a6e76cd67cc',
    firstName: 'Super',
    lastName: 'Admin',
    email: 'admin@example.com',
    password: '$2a$10$95KnyYK2no87yT1ZDTL2QucLTFOPSgkDtThoU0LKhAYA1yPUl6fLe',
  },
  {
    id: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    password: '$2a$10$95KnyYK2no87yT1ZDTL2QucLTFOPSgkDtThoU0LKhAYA1yPUl6fLe',
  },
];

export const shelves = [
  {
    id: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    title: 'Shelf A',
    index: 0,
    isCollapsed: true,
    missedTrainingValue: 'none',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.031Z',
    updatedAt: '2024-01-06T06:38:41.031Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
  },
];

export const boxes = [
  {
    id: '9e5fe6cd-ce8a-4e3f-ab0d-2732633f0db3',
    index: 0,
    timing: {
      days: 0,
      hours: 0,
      weeks: 0,
      months: 0,
      minutes: 5,
    },
    specialType: 'new',
    missedTrainingValue: null,
    isDeleted: false,
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
  },
  {
    id: 'b50ce631-5592-4906-aa31-f1efe81f3eb5',
    index: 1,
    timing: {
      days: 0,
      hours: 0,
      weeks: 0,
      months: 0,
      minutes: 5,
    },
    specialType: 'none',
    missedTrainingValue: null,
    isDeleted: false,
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
  },
  {
    id: '6393744a-ad4b-4280-8a4d-834061de845e',
    index: 2,
    timing: {
      days: 0,
      hours: 8,
      weeks: 0,
      months: 0,
      minutes: 0,
    },
    specialType: 'none',
    missedTrainingValue: null,
    isDeleted: false,
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
  },
  {
    id: 'f04987f4-55e1-498f-9543-773a88771a70',
    index: 3,
    timing: {
      days: 1,
      hours: 0,
      weeks: 0,
      months: 0,
      minutes: 0,
    },
    specialType: 'none',
    missedTrainingValue: null,
    isDeleted: false,
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
  },
  {
    id: 'ecd71dc5-b135-4860-9d87-b0c7fb8fb33f',
    index: 4,
    timing: {
      days: 0,
      hours: 0,
      weeks: 1,
      months: 0,
      minutes: 0,
    },
    specialType: 'none',
    missedTrainingValue: null,
    isDeleted: false,
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
  },
  {
    id: '68e7a429-dff9-4e4b-af21-5405857ceded',
    index: 5,
    timing: {
      days: 0,
      hours: 0,
      weeks: 0,
      months: 1,
      minutes: 0,
    },
    specialType: 'learnt',
    missedTrainingValue: null,
    isDeleted: false,
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
  },
];

export const cards = [
  {
    id: 'd98b6354-ad71-4db1-87f6-1e552bf7a26d',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequa","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"sdfwefwfewf","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequa","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"sdfwefwfewf","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: null,
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '9e5fe6cd-ce8a-4e3f-ab0d-2732633f0db3',
  },
  {
    id: 'f3318e4c-6ea7-4c55-91f4-02d6240e84f9',
    question:
      '{"root":{"children":[{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"sfwefwefwe","type":"text","version":1}],"direction":"ltr","format":"center","indent":0,"type":"listitem","version":1,"value":1}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"},{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"sfwefwefw","type":"text","version":1}],"direction":"ltr","format":"right","indent":0,"type":"listitem","version":1,"value":1}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"number","start":1,"tag":"ol"},{"children":[{"altText":"Yellow flower in tilt shift lens","caption":{"editorState":{"root":{"children":[],"direction":null,"format":"","indent":0,"type":"root","version":1}}},"height":0,"maxWidth":500,"showCaption":false,"src":"/src/shared/ui/lexical-playground/src/images/yellow-flower.jpg","type":"image","version":1,"width":0}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"ацуацу","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"qua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliыва","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"цу","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"ацуацу","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[],"direction":null,"format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"qua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: null,
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '9e5fe6cd-ce8a-4e3f-ab0d-2732633f0db3',
  },
  {
    id: 'db9dbfe3-6720-4246-9e61-b024021d9919',
    question:
      '{"root":{"children":[{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"sfwefwefwe","type":"text","version":1}],"direction":"ltr","format":"center","indent":0,"type":"listitem","version":1,"value":1}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"},{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"sfwefwefw","type":"text","version":1}],"direction":"ltr","format":"right","indent":0,"type":"listitem","version":1,"value":1}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"number","start":1,"tag":"ol"},{"children":[{"altText":"Yellow flower in tilt shift lens","caption":{"editorState":{"root":{"children":[],"direction":null,"format":"","indent":0,"type":"root","version":1}}},"height":0,"maxWidth":500,"showCaption":false,"src":"/src/shared/ui/lexical-playground/src/images/yellow-flower.jpg","type":"image","version":1,"width":0}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"ацуацу","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"qua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: null,
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '9e5fe6cd-ce8a-4e3f-ab0d-2732633f0db3',
  },
  {
    id: '820ba64d-dd21-42c5-8a73-ac8519eab13d',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: null,
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '9e5fe6cd-ce8a-4e3f-ab0d-2732633f0db3',
  },
  {
    id: '0fc11f97-8382-409c-9c09-1354a160d5ce',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: null,
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '9e5fe6cd-ce8a-4e3f-ab0d-2732633f0db3',
  },
  {
    id: '4a30a3a2-3e6b-4046-88c8-c5e842c23110',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'b50ce631-5592-4906-aa31-f1efe81f3eb5',
  },
  {
    id: 'cc4ac736-94a1-4f53-b4d9-b8ce9688466d',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'b50ce631-5592-4906-aa31-f1efe81f3eb5',
  },
  {
    id: 'f1f688a1-221c-46bf-877b-06942ea7a08c',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'b50ce631-5592-4906-aa31-f1efe81f3eb5',
  },
  {
    id: '0635c21b-f631-4f47-badf-170ee059ea5c',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'b50ce631-5592-4906-aa31-f1efe81f3eb5',
  },
  {
    id: '0671b278-2043-4df2-8da0-ed348b22e00f',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'b50ce631-5592-4906-aa31-f1efe81f3eb5',
  },
  {
    id: 'd82ab134-8323-4272-8290-40c87516761d',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '6393744a-ad4b-4280-8a4d-834061de845e',
  },
  {
    id: '41c79512-f2f9-441d-8414-01dab76f7385',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '6393744a-ad4b-4280-8a4d-834061de845e',
  },
  {
    id: 'b9b9b50c-4c12-4c0a-b802-6071114854ab',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '6393744a-ad4b-4280-8a4d-834061de845e',
  },
  {
    id: '73208520-3b62-472f-9a29-31610b6fc053',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '6393744a-ad4b-4280-8a4d-834061de845e',
  },
  {
    id: '6f933a6b-8dea-48bd-9609-872c2f1aa0a1',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '6393744a-ad4b-4280-8a4d-834061de845e',
  },
  {
    id: '3dcf717a-fa49-42ff-ab6c-f1e8993da476',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'f04987f4-55e1-498f-9543-773a88771a70',
  },
  {
    id: 'a45d6ea2-e011-40bf-b145-ce8f85e8e5c1',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'f04987f4-55e1-498f-9543-773a88771a70',
  },
  {
    id: 'b7a46ed2-0873-4f64-b9b0-dccffdae99fa',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'f04987f4-55e1-498f-9543-773a88771a70',
  },
  {
    id: 'aa4fe850-4f78-43c2-93d6-c2dfb6fe6dd1',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'f04987f4-55e1-498f-9543-773a88771a70',
  },
  {
    id: '4c2d7c9e-e6b0-4bce-b044-1784dd67bd0c',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'f04987f4-55e1-498f-9543-773a88771a70',
  },
  {
    id: '65c839aa-ba05-455d-a42a-c99d64951a3d',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'ecd71dc5-b135-4860-9d87-b0c7fb8fb33f',
  },
  {
    id: '22f99728-ca27-4819-b874-a52b2331e038',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'ecd71dc5-b135-4860-9d87-b0c7fb8fb33f',
  },
  {
    id: 'e5fc4d1f-69db-49b6-9040-fcccfa3e5df3',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'ecd71dc5-b135-4860-9d87-b0c7fb8fb33f',
  },
  {
    id: '30ec7b21-33e3-4b3b-a359-f7dec41baa5b',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'ecd71dc5-b135-4860-9d87-b0c7fb8fb33f',
  },
  {
    id: '0132b60c-06e9-4fba-a796-5e9e7aed17c1',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: 'ecd71dc5-b135-4860-9d87-b0c7fb8fb33f',
  },
  {
    id: 'c76cd681-df64-4759-9d4a-ce786a3d85ee',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '68e7a429-dff9-4e4b-af21-5405857ceded',
  },
  {
    id: 'aa0f4365-47bd-4948-ad11-3b492d0156d3',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '68e7a429-dff9-4e4b-af21-5405857ceded',
  },
  {
    id: 'b697e482-aa8c-4922-a60e-b88ceedc631d',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '68e7a429-dff9-4e4b-af21-5405857ceded',
  },
  {
    id: 'c9a23e8a-1b4b-4714-ae2d-f38b319c539a',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '68e7a429-dff9-4e4b-af21-5405857ceded',
  },
  {
    id: '9b8a69ed-cfbe-4b8a-8e53-d6e8f9885445',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: '2024-01-06T06:38:41.173Z',
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '68e7a429-dff9-4e4b-af21-5405857ceded',
  },
];

export const TEST_shelfId = '469f83a0-b3f0-4943-bc02-44c31c7530aa';

export const TEST_boxIdNewCards = '9e5fe6cd-ce8a-4e3f-ab0d-2732633f0db3';

export const TEST_cardsInNewBox = [
  {
    id: 'd98b6354-ad71-4db1-87f6-1e552bf7a26d',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequa","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"sdfwefwfewf","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"type":"linebreak","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequa","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"sdfwefwfewf","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"fwfw","type":"text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"t. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: null,
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '9e5fe6cd-ce8a-4e3f-ab0d-2732633f0db3',
  },
  {
    id: 'f3318e4c-6ea7-4c55-91f4-02d6240e84f9',
    question:
      '{"root":{"children":[{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"sfwefwefwe","type":"text","version":1}],"direction":"ltr","format":"center","indent":0,"type":"listitem","version":1,"value":1}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"},{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"sfwefwefw","type":"text","version":1}],"direction":"ltr","format":"right","indent":0,"type":"listitem","version":1,"value":1}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"number","start":1,"tag":"ol"},{"children":[{"altText":"Yellow flower in tilt shift lens","caption":{"editorState":{"root":{"children":[],"direction":null,"format":"","indent":0,"type":"root","version":1}}},"height":0,"maxWidth":500,"showCaption":false,"src":"/src/shared/ui/lexical-playground/src/images/yellow-flower.jpg","type":"image","version":1,"width":0}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"ацуацу","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"qua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliыва","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"цу","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"ацуацу","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[],"direction":null,"format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"qua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: null,
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '9e5fe6cd-ce8a-4e3f-ab0d-2732633f0db3',
  },
  {
    id: 'db9dbfe3-6720-4246-9e61-b024021d9919',
    question:
      '{"root":{"children":[{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"sfwefwefwe","type":"text","version":1}],"direction":"ltr","format":"center","indent":0,"type":"listitem","version":1,"value":1}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"},{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"sfwefwefw","type":"text","version":1}],"direction":"ltr","format":"right","indent":0,"type":"listitem","version":1,"value":1}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"number","start":1,"tag":"ol"},{"children":[{"altText":"Yellow flower in tilt shift lens","caption":{"editorState":{"root":{"children":[],"direction":null,"format":"","indent":0,"type":"root","version":1}}},"height":0,"maxWidth":500,"showCaption":false,"src":"/src/shared/ui/lexical-playground/src/images/yellow-flower.jpg","type":"image","version":1,"width":0}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"ацуацу","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"qua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: null,
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '9e5fe6cd-ce8a-4e3f-ab0d-2732633f0db3',
  },
  {
    id: '820ba64d-dd21-42c5-8a73-ac8519eab13d',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: null,
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '9e5fe6cd-ce8a-4e3f-ab0d-2732633f0db3',
  },
  {
    id: '0fc11f97-8382-409c-9c09-1354a160d5ce',
    question:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Minim aliqua voluptate Lorem deserunt aute non labore anim in in consequat. Aliqua voluptate nulla eu in.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    answer:
      '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur Aute aute ex esse laboris magna ut voluptate duis tempor reprehenderit. Irure veniam quis ea pariatur","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
    lastTraining: null,
    nextTraining: null,
    isDeleted: false,
    createdAt: '2024-01-06T06:38:41.185Z',
    updatedAt: '2024-01-06T06:38:41.185Z',
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
    boxId: '9e5fe6cd-ce8a-4e3f-ab0d-2732633f0db3',
  },
];

export const TEST_boxesByShelfIdOrderIndex = [
  {
    id: '9e5fe6cd-ce8a-4e3f-ab0d-2732633f0db3',
    index: 0,
    timing: {
      days: 0,
      hours: 0,
      weeks: 0,
      months: 0,
      minutes: 5,
    },
    specialType: 'new',
    missedTrainingValue: null,
    isDeleted: false,
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
  },
  {
    id: 'b50ce631-5592-4906-aa31-f1efe81f3eb5',
    index: 1,
    timing: {
      days: 0,
      hours: 0,
      weeks: 0,
      months: 0,
      minutes: 5,
    },
    specialType: 'none',
    missedTrainingValue: null,
    isDeleted: false,
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
  },
  {
    id: '6393744a-ad4b-4280-8a4d-834061de845e',
    index: 2,
    timing: {
      days: 0,
      hours: 8,
      weeks: 0,
      months: 0,
      minutes: 0,
    },
    specialType: 'none',
    missedTrainingValue: null,
    isDeleted: false,
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
  },
  {
    id: 'f04987f4-55e1-498f-9543-773a88771a70',
    index: 3,
    timing: {
      days: 1,
      hours: 0,
      weeks: 0,
      months: 0,
      minutes: 0,
    },
    specialType: 'none',
    missedTrainingValue: null,
    isDeleted: false,
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
  },
  {
    id: 'ecd71dc5-b135-4860-9d87-b0c7fb8fb33f',
    index: 4,
    timing: {
      days: 0,
      hours: 0,
      weeks: 1,
      months: 0,
      minutes: 0,
    },
    specialType: 'none',
    missedTrainingValue: null,
    isDeleted: false,
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
  },
  {
    id: '68e7a429-dff9-4e4b-af21-5405857ceded',
    index: 5,
    timing: {
      days: 0,
      hours: 0,
      weeks: 0,
      months: 1,
      minutes: 0,
    },
    specialType: 'learnt',
    missedTrainingValue: null,
    isDeleted: false,
    deletedAt: null,
    userId: '48a27e6a-4fa9-4cd5-8c7f-c6007ffb0fe2',
    shelfId: '469f83a0-b3f0-4943-bc02-44c31c7530aa',
  },
];
